---
- name: Install fish
  become: yes
  package:
    name: fish
    state: present

- name: Install my fish configuration
  vars:
    fish_config_dir: "{{ lookup('env', 'HOME') }}/.config/fish"
  block:
    - file:
        dest: "{{ fish_config_dir }}"
        state: directory
    - copy:
        src: files/config.fish
        dest: "{{ fish_config_dir }}/config.fish"

- when: lookup('env', 'SHELL') != '/usr/bin/fish'
  block:
    - pip:
        name: pexpect
      become: yes

    - pause:
        prompt: "Enter your password to run chsh: "
        echo: no
      register: password

    - expect:
        command: "chsh -s /usr/bin/fish"
        responses:
          Password: "{{ password.user_input }}"
