---
- hosts: all
  roles:
    - name: fish
    - name: git-config
    - name: fcitx
  tasks:
    - lineinfile:
        create: yes
        line: 'XKBOPTIONS="ctrl:nocaps"'
        path: /etc/default/keyboard
        regexp: '^XKBOPTIONS='
      become: yes
