---
- hosts: all
  roles:
    - name: fish
    - name: git-config
  tasks:
    - name: Install a desktop file to set ctrl:nocaps setxkbmap option
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.config/autostart/nocaps.desktop"
        src: files/nocaps.desktop
